### ISSUE TITLE
Automatic reset feature malfunctioning

### ISSUE THREAD

**Issue by frostidllo** [Dalet/LiveSplit.UnrealLoads#11]
Hello, there are multiple issues with automatic reset feature.

- The checkbox in options randomly checks and unchecks so it's not the same every time.

- Sometimes (or always?) the function will reset the timer after one game is finished in a multigame run, ruining the entire run. Note that this had happened many times in past and it's extremely frustrating when you are forced to end a run because of a bug that was not even your fault. Example of the timer resetting after HP1 in Octofecta run: https://clips.twitch.tv/CleanPluckyAardvarkBuddhaBar

- Automatic reset doesn't really make sense to me as a speedrunner. I see the point of automatic splits and even starting and ending the timer because all these things are technically a part of the run and it is saving your time and you can focus more on the actual game. However if you really want to reset, there is literally no point of saving time, because you are already willingly giving up on the time you got either during the run or after you are finished with it.
This feature saves you pressing one button in a situation where you don't need to do it quick but at the same time it's playing with fire because in a good attempt, the last thing you want is to press the reset button. And allowing some third party to press the button for you when it's out of your control is generally very bad idea. There were multiple occasions in Harry Potter speedrunnning community like this, where this feature ruined people's runs and I believe there is nobody who is actually using this feature.

I think that the best would be to completely remove this feature from the Auto Splitter or at least make sure that it is unchecked on default in settings and it doesn't change on random.

Thanks in advance, I appreciate your work 👍

**Comment by TheTedder** [comment]
Hi, sorry I completely missed this. I was able to replicate this bug just from casually using the timer. These are really two separate issues. The first issue is autoreset randomly turning itself on. I'll look into this and see if I can deduce why it's happening and push a fix. The second issue: why is autoreset even a thing? I have no idea to be honest. It only exists to screw you over because you left it on by accident; however, there will inevitably be someone who whines about us inconveniencing them by removing a feature that saves them one button press. I'm gonna go ahead and mention @Dalet to see what he thinks, as he's the owner of the plugin. I'm all for removing it personally.

**Comment by Dalet** [comment]
I won't argue about the value of auto-reset as a feature here.

Usually auto-reset is implemented better and you can't reasonably reset accidentally. But for Harry Potter it's basically just when starting the game... so I'll remove it for Harry Potter for now.

> The checkbox in options randomly checks and unchecks so it's not the same every time.

I doubt this is an autosplitter bug, the settings code hasn't changed in years. You have to keep in mind that autosplitter settings are saved in the splits file, so if you don't save your splits the settings won't be saved. Also if you make new splits the settings are reset to defaults.

**Comment by Dalet** [comment]
Closing since auto-reset is removed for HP2 in v1.8 released today.
